# firstLineForSale:       List of options for the first line of a sign to sell
# firstLineForRent:       List of options for the first line of a sign to rent out
# 
# blockWorth:             The general worth of one block in a protected region.
# 
#                             In this case, one block actually means a vertical column of blocks, 
#                             from coordinates defaultBottomY to defaultTopY.
# 
#                             If blockWorth is 0.22, a region with a size of 10x10 would be worth 22. 
#                             Use the worth command to make these calculations.
# 
# maxRegionsPerPlayer:  What is the maximum amount of regions a player can have (per world)
#                         This value is checked when claiming a region, not when creating one
# onBuy:                When a player buys a region...
#   reserveFreeRegions:   Whether to reserve Free regions for new players. (players without a region)
# 
# onCreate:             When a player creates a region...
#   enableCost:           Does a player need to pay the region worth (and become owner)
#   automaticParent:      Is the region's parent set automatically. 
# 
#                             An automatic parent will always be a cuboid region wherein the new region exists completely.
#                             When there are more of these big regions, the highest priority region will be the parent.
#                             When priorities are equal, the smallest region will be the parent.
# 
#   defaultOwners:        Who will automatically be owners of new regions. If this list is empty,
#                         the owner will be the player that creates the region.
# 
#   defaultTopY:          What will automatically be the highest y-coordinate of new regions
#   defaultBottomY:       What will automatically be the lowest y-coordinate of new regions
# 
#   allowOverlapUnownedRegions: true/false
# 
# sizes:                Region size boundries
#   minimumY:             The smallest allowed bottom coordinate
#   maximumY:             The largest allowed top coordinate
#   
#   minimumHeight:        The smallest allowed height
#   maximumHeight:        The largest allowed height
#                         
#                         The vertical boundries don't apply to the defaultTopY and defaultBottomY
#   
#   minimumWidthLength:   The smallest allowed width and length
#   maximumWidthLength:   The largest allowed with and length
#   
# onDelete:             When a player deletes a region...
#   refundPercent:        How much percent of the region's worth will be refunded to the owners
#   
# onSell:               When a player puts a region up for sale...
#   minBlockCost:         What is the minimum price for each block in a region
#   maxBlockCost:         What is the maximum price for each block in a region
#   
#                         In most cases it's recommended to keep the value of blockWorth  
#                         between the values of minBlockCost and maxBlockCost
# 
#   tax:
#     account:            Which account will receive the tax
#     from-price:         You must pay tax, when you receive this much money
#     percent:            You pay this much percent of your earnings to the tax-account
#   
# onRent:               When a player puts a region up for rent...
#   minBlockCost:         What is the minimum price for each block in a region, per time unit
#   maxBlockCost:         What is the maximum price for each block in a region, per time unit
#   maxHours:             What is the maximum amount of hours that a region can be rented for
# 
# enable-permission.bypasscost: For the people that have permission problems
# 
firstLineForSale:
  - For Sale
firstLineForRent:
  - For Rent
blockWorth: 0.22
maxRegionsPerPlayer: 5
onBuy:
  reserveFreeRegions: true
onCreate:
  enableCost: false
  automaticParent: false
  defaultOwners: []
  defaultBottomY: 0
  defaultTopY: 127
  sizes:
    minimumY: 0
    maximumY: 127
    minimumHeight: 8
    maximumHeight: 127
    minimumWidthLength: 8
    maximumWidthLength: 100
  allowOverlapUnownedRegions: false
onDelete:
  refundPercent: 50
onSell:
  minBlockCost: 0.20
  maxBlockCost: 0.50
  tax:
    account: Mtihc
    from-price: 100
    percent: 19
onRent:
  minBlockCost: 0.002
  maxBlockCost: 0.005
  maxHours: 24
enable-permission:
  bypasscost: true