# 
# sign-first-line
#   for-rent:             List of options for the first line of a For-Rent sign
#   for-sale:             List of options for the first line of a For-Sale sign
# 
sign-first-line:
  for-rent:
  - For Rent
  for-sale:
  - For Sale